- id: 31c41e08480f4761ba1d84bc379b5df9
  alias: Coffee weekday warmup
  hide_entity: false
  trigger:
    platform: time
    at: 06:45:00
  condition:
    condition: and
    conditions:
    - condition: zone
      entity_id: device_tracker.hunter_hunterspixel
      zone: zone.home
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: homeassistant.turn_on
    entity_id:
    - switch.Silvia
- id: aa91ac10b76049d7b8c36c20a3ad03c3
  alias: Notify of Rain
  hide_entity: false
  trigger:
    platform: time
    at: 06:55:00
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: numeric_state
      entity_id: sensor.weather_precip_probability
      above: 30
  action:
  - service: notify.pushbullet
    data:
      message: Rain is expected today
- id: 74fc02fd98a345c7bcd41cddf1d320cd
  alias: Certificate Expiry Warning
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.ssl_certificate_expiry
    from: '4'
    to: '3'
  action:
    service: notify.pushbullet
    data:
      message: HomeAssistant certificate expiring in 3 days
- id: 61ef041cedc14cc29a3087d02c67bc17
  alias: Turn off things I left on
  hide_entity: false
  trigger:
    platform: state
    entity_id: group.Family
    from: home
    to: not_home
  action:
  - service: homeassistant.turn_off
    entity_id:
    - group.Lounge_Room
    - light.Study
    - switch.Silvia
    - switch.PC
    - switch.gym_speakers
    - light.Bedroom
    - light.Entry
    - light.Hallway
    - light.Stairs
- id: fecafe1ec73542aab9b1ef636facefc5
  alias: Left Music On
  hide_entity: false
  trigger:
    platform: state
    entity_id: group.Family
    from: home
    to: not_home
  condition:
    condition: state
    entity_id: media_player.tunes
    state: playing
  action:
  - service: media_player.media_pause
    entity_id: media_player.tunes
- id: 412246de78934e02aa2d405cbe00a214
  alias: Turn the lights on when we arrive at night
  hide_entity: true
  trigger:
    platform: state
    entity_id: device_tracker.hunter_hunterspixel, device_tracker.nikki_nikkisz3
    from: not_home
    to: home
  condition:
    condition: or
    conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
  action:
  - service: notify.pushbullet
    data:
      message: Welcome home
  - service: homeassistant.turn_on
    entity_id: light.entry
- id: d823f6cba3b54bf1848db1a2e9820d00
  alias: Dim the lights when we watch Plex
  hide_entity: false
  trigger:
  - platform: state
    entity_id: sensor.Plex
    from: '0'
    to: '1'
  condition:
    condition: state
    entity_id: media_player.samsung_tv
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_dim
- id: '1520327583216'
  alias: Turn on the lights with the tv
  trigger:
  - entity_id: media_player.samsung_tv
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: light.lounge
    service: light.turn_on
  condition:
  - after: sunset
    condition: sun
- action:
  - data:
      entity_id: scene.alarm
    service: scene.turn_on
  alias: Weekend Alarm
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.hunter_hunterspixel
      state: home
    - condition: time
      weekday:
      - sat
      - sun
  id: '1520409505164'
  trigger:
    platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.weekend_wakeup_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
- action:
  - data:
      entity_id: switch.gym_speakers
    service: switch.turn_on
  alias: Turn on gym speakers with Chromecast
  condition: []
  id: '1521017777150'
  trigger:
  - entity_id: media_player.chromecastaudio4835
    platform: state
    to: playing
- action:
  - data:
      entity_id: switch.gym_speakers
    service: switch.turn_off
  alias: Turn off the gym speaker when no longer listening
  condition: []
  id: '1521018025766'
  trigger:
  - entity_id: media_player.chromecastaudio4835
    platform: state
    to: paused
    for:
      seconds: 30
- action:
  - data:
      message: Water leak detected!
    service: notify.pushbullet
  alias: Water Alarm
  condition: []
  id: '1524401072541'
  trigger:
  - entity_id: binary_sensor.water_leak_sensor_158d0002115f31
    from: 'off'
    platform: state
- action:
  - data:
      message: Garage door opened
    service: notify.pushbullet
  alias: Garage Door Alarm
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: device_tracker.hunter_hunterspixel
      state: not_home
    - condition: state
      entity_id: device_tracker.hunter_hunterspixel
      state: work
  id: '1524401200558'
  trigger:
  - entity_id: cover.garage_door
    platform: state
    to: open
    for:
      minutes: 2
- action:
  - data:
      entity_id: light.gateway_light_7811dcb20b46
    service: light.turn_on
  alias: Turn on the pantry light
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  id: '1525093789395'
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001b1b1ba
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: light.gateway_light_7811dcb20b46
    service: light.turn_off
  alias: Turn off the pantry light
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  id: '1525094152925'
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001b1b1ba
    platform: state
    to: 'off'
- action:
  - service: light.turn_off
  alias: Long press bedside button
  condition: []
  id: '1525094445197'
  trigger:
  - entity_id: binary_sensor.switch_158d0001f40663
    platform: state
    to: hold
- action:
  - data:
      entity_id: switch.plug_158d00020f3b00
    service: switch.turn_on
  alias: Turn on the bathroom fan
  condition:
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d0001b77bc5
    state: 'off'
  id: '1525682046813'
  trigger:
  - entity_id: sensor.shower_on
    platform: state
    to: 'True'
- action:
  - data:
      entity_id: switch.plug_158d00020f3b00
    service: switch.turn_off
  alias: Turn off the bathroom fan
  condition: []
  id: '1525682254042'
  trigger:
  - entity_id: sensor.shower_on
    platform: state
    to: 'False'
  - entity_id: binary_sensor.door_window_sensor_158d0001b77bc5
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: switch.plug_158d00020f3b00
    service: switch.turn_on
  alias: Turn on the bathroom fan with the door
  condition:
  - condition: state
    entity_id: sensor.shower_on
    state: 'True'
  id: '1525686734650'
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001b77bc5
    for:
      seconds: 6
    platform: state
    to: 'off'
- action:
  - service: light.turn_off
  alias: Turn off lights
  condition: []
  id: '1525698358651'
  trigger:
  - entity_id: binary_sensor.switch_158d0001f40663
    platform: state
    to: 'on'
