- id: 31c41e08480f4761ba1d84bc379b5df9
  alias: Coffee weekday warmup
  hide_entity: false
  trigger:
    platform: time
    at: 06:45:00
  condition:
    condition: and
    conditions:
    - condition: zone
      entity_id: person.hunter
      zone: zone.home
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: homeassistant.turn_on
    entity_id:
    - switch.Silvia
- id: aa91ac10b76049d7b8c36c20a3ad03c3
  alias: Notify of Rain
  hide_entity: false
  trigger:
    platform: time
    at: 06:55:00
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: numeric_state
      entity_id: sensor.weather_precip_probability
      above: 10
  action:
  - service: notify.pushbullet
    data:
      message: Rain is expected today
- id: 74fc02fd98a345c7bcd41cddf1d320cd
  alias: Certificate Expiry Warning
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.ssl_certificate_expiry
    from: '4'
    to: '3'
  action:
    service: notify.pushbullet
    data:
      message: HomeAssistant certificate expiring in 3 days
- id: 61ef041cedc14cc29a3087d02c67bc17
  alias: Turn off things I left on
  trigger:
  - entity_id: group.Family
    for: '300'
    from: home
    platform: state
    to: not_home
  action:
  - entity_id:
    - group.Lounge_Room
    - light.Study
    - switch.Silvia
    - switch.PC
    - switch.gym_speakers
    - light.Bedroom
    - light.Entry
    - light.Hallway
    - light.Stairs
    service: homeassistant.turn_off
  hide_entity: false
- id: fecafe1ec73542aab9b1ef636facefc5
  alias: Left Music On
  hide_entity: false
  trigger:
    platform: state
    entity_id: group.Family
    from: home
    to: not_home
  condition:
    condition: state
    entity_id: media_player.tunes
    state: playing
  action:
  - service: media_player.media_pause
    entity_id: media_player.tunes
- id: d823f6cba3b54bf1848db1a2e9820d00
  alias: Dim the lights when we watch Plex
  hide_entity: false
  trigger:
  - platform: state
    entity_id: sensor.Plex
    from: '0'
    to: '1'
  condition:
    condition: state
    entity_id: media_player.samsung_tv
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_dim
- id: '1520327583216'
  alias: Turn on the lights with the tv
  trigger:
  - entity_id: media_player.living_room_tv
    from: 'off'
    platform: state
    to: playing
  - event: sunset
    offset: '-60'
    platform: sun
  condition:
  - after: sunset
    after_offset: '-60'
    condition: sun
  - condition: state
    entity_id: media_player.living_room_tv
    state: playing
  action:
  - data:
      entity_id: light.lounge
    service: light.turn_on
- id: '1520409505164'
  alias: Weekend Alarm
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.weekend_wakeup_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: person.hunter
      state: home
    - condition: time
      weekday:
      - sat
      - sun
  action:
  - data:
      entity_id: scene.alarm
    service: scene.turn_on
  - data: {}
    service: script.delayed_alarm
- action:
  - data:
      entity_id: switch.gym_speakers
    service: switch.turn_on
  alias: Turn on gym speakers with Chromecast
  condition: []
  id: '1521017777150'
  trigger:
  - entity_id: media_player.chromecastaudio4835
    platform: state
    to: playing
- id: '1521018025766'
  alias: Turn off the gym speaker when no longer listening
  trigger:
  - entity_id: media_player.chromecastaudio4835
    for:
      seconds: 30
    platform: state
    to: paused
  - entity_id: media_player.chromecastaudio4835
    for: 0:00:30
    from: playing
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.gym_speakers
    service: switch.turn_off
- id: '1524401072541'
  alias: Water Alarm
  trigger:
  - entity_id: binary_sensor.water_leak_sensor_158d0002115f31
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Water leak detected near aquarium!
      target:
        - !secret nikki_pushbullet
        - !secret hunter_pushbullet
    service: notify.pushbullet
- id: '1524401200558'
  alias: Garage Door Alarm
  trigger:
  - entity_id: cover.garage_door
    for:
      minutes: 2
    platform: state
    to: open
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: person.hunter
      state: not_home
    - condition: state
      entity_id: person.hunter
      state: work
  action:
  - data:
      message: Garage door opened
      target:
        - !secret nikki_pushbullet
        - !secret hunter_pushbullet
    service: notify.pushbullet
- id: '1525093789395'
  alias: Turn on the pantry light
  trigger:
  - entity_id: binary_sensor.pantry_door
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id:
      - light.pantry
    service: light.turn_on
- id: '1525094152925'
  alias: Turn off the pantry light
  trigger:
  - entity_id: binary_sensor.pantry_door
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id:
      - light.gateway_light_7811dcb20b46
      - light.pantry
    service: light.turn_off
- id: '1525094445197'
  alias: Press bedside button
  trigger:
    topic: zigbee2mqtt/bedside_button
    platform: mqtt
  condition:
    condition: template
    value_template: '{{ "single" == trigger.payload_json.click }}'
  action:
  - data:
      entity_id: all
    service: light.turn_off
- id: '1525682046813'
  alias: Turn on the bathroom fan
  trigger:
  - entity_id: sensor.shower_on
    platform: state
    to: 'True'
  condition:
  - condition: state
    entity_id: binary_sensor.bathroom_door
    state: 'off'
  action:
  - data:
      entity_id: switch.0x00158d00020f3b00_switch
    service: switch.turn_on
- id: '1525682254042'
  alias: Turn off the bathroom fan
  trigger:
  - entity_id: sensor.shower_on
    platform: state
    to: 'False'
  - entity_id: binary_sensor.bathroom_door
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.0x00158d00020f3b00_switch
    service: switch.turn_off
- id: '1525686734650'
  alias: Turn on the bathroom fan with the door
  trigger:
  - entity_id: binary_sensor.bathroom_door
    for:
      seconds: 6
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sensor.shower_on
    state: 'True'
  action:
  - data:
      entity_id: switch.0x00158d00020f3b00_switch
    service: switch.turn_on
- id: '1529573776011'
  alias: Weekday Alarm
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.weekday_wakeup_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: person.hunter
    state: home
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - fri
  action:
  - data:
      entity_id: scene.Alarm
    service: scene.turn_on
  - alias: ''
    data:
      brightness_pct: 5
      color_temp: 1
      entity_id: light.bedroom
    service: light.turn_on
  - alias: ''
    data: {}
    service: script.delayed_alarm
- id: '1544439026982'
  alias: Set Initial States
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: homeassistant.turn_on
    entity_id: switch.flux
- id: '1553416932251'
  alias: Turn on the lights when we arrive at night
  trigger:
  - entity_id: person.hunter
    platform: state
    to: home
  - entity_id: binary_sensor.0x00158d0001f38110_contact
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: person.nikki
    from: not_home
    platform: state
    to: home
  condition:
  - condition: or
    conditions:
    - after: sunset
      after_offset: '-1:00:00'
      condition: sun
    - before: sunrise
      before_offset: '1:00:00'
      condition: sun
  action:
  - alias: ''
    entity_id: light.entry
    service: light.turn_on
  - service: script.delayed_entry_off
- id: '1554985557227'
  alias: Weekday Peak NonWinter Tariff Set
  trigger:
  - at: '13:59'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: utility_meter.energy
      tariff: peak
    service: utility_meter.select_tariff
- id: '1554985959342'
  alias: Weekday Shoulder NonWinter Tariff Set
  trigger:
  - at: '20:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: utility_meter.energy
      tariff: shoulder
    service: utility_meter.select_tariff
- id: '1555116275673'
  alias: Kitchen timer notification
  trigger:
  - below: '1'
    entity_id: sensor.display_timer_remaining
    for: '30'
    platform: numeric_state
  condition: []
  action:
  - data:
      message: The kitchen display timer is ready
      target:
        - !secret nikki_pushbullet
        - !secret hunter_pushbullet
    service: notify.pushbullet
- id: '1555116490673'
  alias: Weekday Peak Winter Tariff Set
  initial_state: 'false'
  trigger:
  - at: '16:59'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: utility_meter.energy
      tariff: peak
    service: utility_meter.select_tariff
- id: '1555121570851'
  alias: Transition Winter Tariffs
  trigger:
  - entity_id: sensor.season
    from: autumn
    platform: state
    to: winter
  - entity_id: sensor.season
    from: winter
    platform: state
    to: autumn
  condition: []
  action:
  - data:
      entity_id: automation.Weekday_Peak_NonWinter_Tariff_Set
    service: automation.toggle
  - data:
      entity_id: automation.Weekday_Peak_Winter_Tariff_Set
    service: automation.toggle
  - data:
      entity_id: automation.Weekday_Shoulder_NonWinter_Tariff_Set
    service: automation.toggle
  - data:
      entity_id: automation.Weekday_Shoulder_Winter_Tariff_Set
    service: automation.toggle
- id: '1555549536072'
  alias: Power Usage Alarm
  trigger:
  - above: '10'
    entity_id: sensor.power_meter
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Power usage above 10 kW,
      target:
        - !secret nikki_pushbullet
        - !secret hunter_pushbullet
    service: notify.pushbullet
- id: '1556932609086'
  alias: Daily Tariff Offpeak Set
  trigger:
  - at: '22:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: utility_meter.energy
      tariff: offpeak
    service: utility_meter.select_tariff
- id: '1556936991072'
  alias: Daily Shoulder Tariff Set
  trigger:
  - at: 07:00
    platform: time
  condition: []
  action:
  - data:
      entity_id: utility_meter.energy
      tariff: shoulder
    service: utility_meter.select_tariff
- id: '1556937862250'
  alias: Weekday Shoulder Winter Tariff Set
  trigger:
  - at: '21:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: utility_meter.energy
      tariff: shoulder
    service: utility_meter.select_tariff
- id: '1558438822399'
  alias: Water Alarm - Laundry
  trigger:
  - entity_id: binary_sensor.0x00158d0002337473_water_leak
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Leak detected in the laundry!
      target:
        - !secret nikki_pushbullet
        - !secret hunter_pushbullet
    service: notify.pushbullet
- id: '1558438953950'
  alias: Water Alarm - Guest Bathroom
  trigger:
  - entity_id: binary_sensor.0x00158d000233865a_water_leak
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Leak detected in the guest bathroom!
      target:
        - !secret nikki_pushbullet
        - !secret hunter_pushbullet
    service: notify.pushbullet
- id: '1558516249730'
  alias: Enable Zigbee joining
  hide_entity: true
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'on'
  condition: []
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'true'
  - service: timer.start
    data:
      entity_id: timer.zigbee_permit_join
- id: disable_zigbee_join
  alias: Disable Zigbee joining
  hide_entity: true
  trigger:
  - entity_id: input_boolean.zigbee_permit_join
    platform: state
    to: 'off'
  action:
  - data:
      payload: 'false'
      topic: zigbee2mqtt/bridge/config/permit_join
    service: mqtt.publish
  - data:
      entity_id: timer.zigbee_permit_join
    service: timer.cancel
- id: disable_zigbee_join_timer
  alias: Disable Zigbee joining by timer
  hide_entity: true
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.zigbee_permit_join
  action:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/bridge/config/permit_join
      payload: 'false'
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.zigbee_permit_join
- alias: Zigbee2mqtt Log Level
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_select.zigbee2mqtt_log_level
    to: debug
  - platform: state
    entity_id: input_select.zigbee2mqtt_log_level
    to: warn
  - platform: state
    entity_id: input_select.zigbee2mqtt_log_level
    to: error
  - platform: state
    entity_id: input_select.zigbee2mqtt_log_level
    to: info
  action:
  - service: mqtt.publish
    data:
      payload_template: '{{ states(''input_select.zigbee2mqtt_log_level'') }}'
      topic: zigbee2mqtt/bridge/config/log_level
  id: 8e75a073763c4e26a1fce569505a812b
- id: '1558569759493'
  alias: Sunrise
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - delay: '1'
- id: '1559638954100'
  alias: Doorbell
  trigger:
  - platform: mqtt
    topic: zigbee2mqtt/0x00158d0002afaf9d
  condition:
  - condition: or
    conditions:
    - condition: template
      value_template: '{{ "single" == trigger.payload_json.click }}'
    - condition: template
      value_template: '{{ "hold" == trigger.payload_json.action }}'
  action:
  - data:
      entity_id: media_player.all_speakers
      volume_level: 0.8
    service: media_player.volume_set
  - data:
      entity_id: media_player.all_speakers
      media_content_id: !secret doorbell_file
      media_content_type: music
    service: media_player.play_media
  - data:
      message: Someone is at the door
      target:
        - !secret nikki_pushbullet
        - !secret hunter_pushbullet
    service: notify.pushbullet
  - data: {}
    service: script.delayed_doorbell
  - data: {}
    service: script.doorbell_trigger
  - data:
      entity_id: media_player.living_room_tv
    service: media_player.media_pause
- id: '1562639972083'
  alias: Aquarium Alerts
  trigger:
  - above: '28'
    below: '22'
    entity_id: sensor.aquarium_temperature
    for: 0:05:00
    platform: numeric_state
  - above: '110'
    below: '85'
    entity_id: sensor.aquarium_water_level
    for: 0:05:00
    platform: numeric_state
  condition: []
  action:
  - data:
      message: Check on the aquarium
      target:
        - !secret hunter_pushbullet
    service: notify.pushbullet
