- id: 31c41e08480f4761ba1d84bc379b5df9
  alias: Coffee weekday warmup
  hide_entity: False
  trigger:
    platform: time
    at: '06:45:00'
  condition:
    condition: and
    conditions:
      - condition: zone
        entity_id: device_tracker.hunter_hunterspixel
        zone: zone.home
      - condition: time
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.Silvia

- id: aa91ac10b76049d7b8c36c20a3ad03c3
  alias: Notify of Rain
  hide_entity: False
  trigger:
    platform: time
    at: '06:55:00'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:        
        - mon
        - tue
        - wed
        - thu
        - fri
      - condition: numeric_state
        entity_id: sensor.weather_precip_probability
        above: 30
  action:
    service: notify.pushbullet
    data:
      message: 'Rain is expected today'

- id: 74fc02fd98a345c7bcd41cddf1d320cd
  alias: Certificate Expiry
  hide_entity: True
  trigger:
    platform: state
    entity_id: sensor.ssl_certificate_expiry
    from: '8'
    to: '7'
  action:
    service: notify.pushbullet
    data:
      message: 'HomeAssistant certificate expiring in 7 days'

- id: 61ef041cedc14cc29a3087d02c67bc17
  alias: Left Lights On
  hide_entity: False
  trigger:
    platform: state
    entity_id: group.Family
    from: 'home'
    to: 'not_home'
  action:
    - service: homeassistant.turn_off
      entity_id: 
        - group.Lounge_Room
        - light.Study
        - switch.Silvia
        - light.Bedroom
        - light.Entry
        - light.Hallway
        - light.Stairs

- id: fecafe1ec73542aab9b1ef636facefc5
  alias: Left Music On
  hide_entity: False
  trigger:
    platform: state
    entity_id: group.Family
    from: 'home'
    to: 'not_home'
  condition:
    condition: state
    entity_id: media_player.tunes
    state: 'playing'
  action:
    - service: media_player.media_pause
      entity_id: media_player.tunes

- id: 06f124acc60a49fc9c85b33e579d5f94
  alias: Arrival Notify
  hide_entity: True
  trigger:
    platform: state
    entity_id: device_tracker.nikki_nikkisz3
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: device_tracker.hunter_hunterspixel
    state: 'home'
  action:
    service: notify.pushbullet
    data:
      message: 'Nikki is home'

- id: 412246de78934e02aa2d405cbe00a214
  alias: Arrival
  hide_entity: True
  trigger:
    platform: state
    entity_id: group.family
    from: 'not_home'
    to: 'home'
  condition: 
    condition: or
    conditions:
      - condition: sun
        after: sunset
      - condition: sun
        before: sunrise
  action:
    service: homeassistant.turn_on
    entity_id: light.entry

- id: d823f6cba3b54bf1848db1a2e9820d00
  alias: "Media player playing"
  hide_entity: False
  trigger:
    - platform: state
      entity_id: sensor.Plex
      from: '0'
      to: '1'
  condition:
    condition: state
    entity_id: media_player.tv
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_dim
      
