- id: 31c41e08480f4761ba1d84bc379b5df9
  alias: Coffee weekday warmup
  hide_entity: false
  trigger:
    platform: time
    at: 06:45:00
  condition:
    condition: and
    conditions:
    - condition: zone
      entity_id: person.hunter
      zone: zone.home
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: homeassistant.turn_on
    entity_id:
    - switch.Silvia
- id: aa91ac10b76049d7b8c36c20a3ad03c3
  alias: Notify of Rain
  hide_entity: false
  trigger:
    platform: time
    at: 06:55:00
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: numeric_state
      entity_id: sensor.weather_precip_probability
      above: 10
  action:
  - service: notify.pushbullet
    data:
      message: Rain is expected today
- id: 74fc02fd98a345c7bcd41cddf1d320cd
  alias: Certificate Expiry Warning
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.ssl_certificate_expiry
    from: '4'
    to: '3'
  action:
    service: notify.pushbullet
    data:
      message: HomeAssistant certificate expiring in 3 days
- id: 61ef041cedc14cc29a3087d02c67bc17
  alias: Turn off things I left on
  trigger:
  - entity_id: group.Family
    for: '300'
    from: home
    platform: state
    to: not_home
  action:
  - entity_id:
    - group.Lounge_Room
    - light.Study
    - switch.Silvia
    - switch.PC
    - switch.gym_speakers
    - light.Bedroom
    - light.Entry
    - light.Hallway
    - light.Stairs
    service: homeassistant.turn_off
  hide_entity: false
- id: fecafe1ec73542aab9b1ef636facefc5
  alias: Left Music On
  hide_entity: false
  trigger:
    platform: state
    entity_id: group.Family
    from: home
    to: not_home
  condition:
    condition: state
    entity_id: media_player.tunes
    state: playing
  action:
  - service: media_player.media_pause
    entity_id: media_player.tunes
- id: d823f6cba3b54bf1848db1a2e9820d00
  alias: Dim the lights when we watch Plex
  hide_entity: false
  trigger:
  - platform: state
    entity_id: sensor.Plex
    from: '0'
    to: '1'
  condition:
    condition: state
    entity_id: media_player.samsung_tv
    state: 'on'
  action:
    service: scene.turn_on
    entity_id: scene.livingroom_dim
- id: '1520327583216'
  alias: Turn on the lights with the tv
  trigger:
  - entity_id: media_player.living_room_tv
    from: 'off'
    platform: state
    to: playing
  - event: sunset
    offset: '-60'
    platform: sun
  condition:
  - after: sunset
    after_offset: '-60'
    condition: sun
  - condition: state
    entity_id: media_player.living_room_tv
    state: playing
  action:
  - data:
      entity_id: light.lounge
    service: light.turn_on
- action:
  - data:
      entity_id: scene.alarm
    service: scene.turn_on
  alias: Weekend Alarm
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: person.hunter
      state: home
    - condition: time
      weekday:
      - sat
      - sun
  id: '1520409505164'
  trigger:
    platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.weekend_wakeup_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
- action:
  - data:
      entity_id: switch.gym_speakers
    service: switch.turn_on
  alias: Turn on gym speakers with Chromecast
  condition: []
  id: '1521017777150'
  trigger:
  - entity_id: media_player.chromecastaudio4835
    platform: state
    to: playing
- id: '1521018025766'
  alias: Turn off the gym speaker when no longer listening
  trigger:
  - entity_id: media_player.chromecastaudio4835
    for:
      seconds: 30
    platform: state
    to: paused
  - entity_id: media_player.chromecastaudio4835
    for: 0:00:30
    from: playing
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.gym_speakers
    service: switch.turn_off
- id: '1524401072541'
  alias: Water Alarm
  trigger:
  - entity_id: binary_sensor.water_leak_sensor_158d0002115f31
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      message: Water leak detected near aquarium!
    service: notify.pushbullet
- action:
  - data:
      message: Garage door opened
    service: notify.pushbullet
  alias: Garage Door Alarm
  condition:
    condition: or
    conditions:
    - condition: state
      entity_id: person.hunter
      state: not_home
    - condition: state
      entity_id: person.hunter
      state: work
  id: '1524401200558'
  trigger:
  - entity_id: cover.garage_door
    platform: state
    to: open
    for:
      minutes: 2
- id: '1525093789395'
  alias: Turn on the pantry light
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001b1b1ba
    platform: state
    to: 'on'
  condition:
  - after: sunset
    after_offset: -02:00:00
    condition: sun
  action:
  - data:
      entity_id:
      - light.gateway_light_7811dcb20b46
      - light.pantry
    service: light.turn_on
- id: '1525094152925'
  alias: Turn off the pantry light
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001b1b1ba
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id:
      - light.gateway_light_7811dcb20b46
      - light.pantry
    service: light.turn_off
- id: '1525094445197'
  alias: Long press bedside button
  trigger:
  - entity_id: binary_sensor.switch_158d0001f40663
    platform: state
    to: hold
  condition: []
  action:
  - data:
      entity_id: all
    service: light.turn_off
- action:
  - data:
      entity_id: switch.plug_158d00020f3b00
    service: switch.turn_on
  alias: Turn on the bathroom fan
  condition:
  - condition: state
    entity_id: binary_sensor.door_window_sensor_158d0001b77bc5
    state: 'off'
  id: '1525682046813'
  trigger:
  - entity_id: sensor.shower_on
    platform: state
    to: 'True'
- action:
  - data:
      entity_id: switch.plug_158d00020f3b00
    service: switch.turn_off
  alias: Turn off the bathroom fan
  condition: []
  id: '1525682254042'
  trigger:
  - entity_id: sensor.shower_on
    platform: state
    to: 'False'
  - entity_id: binary_sensor.door_window_sensor_158d0001b77bc5
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: switch.plug_158d00020f3b00
    service: switch.turn_on
  alias: Turn on the bathroom fan with the door
  condition:
  - condition: state
    entity_id: sensor.shower_on
    state: 'True'
  id: '1525686734650'
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0001b77bc5
    for:
      seconds: 6
    platform: state
    to: 'off'
- action:
  - service: light.turn_off
  alias: Turn off lights
  condition: []
  id: '1525698358651'
  trigger:
  - entity_id: binary_sensor.switch_158d0001f40663
    platform: state
    to: 'on'
- id: '1529573776011'
  alias: Weekday Alarm
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.weekday_wakeup_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: person.hunter
    state: home
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - fri
  action:
  - data:
      entity_id: scene.Alarm
    service: scene.turn_on
- id: '1544439026982'
  alias: Set Initial States
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - service: homeassistant.turn_on
    entity_id: switch.flux
- id: '1553416932251'
  alias: Turn on the lights when we arrive at night
  trigger:
  - entity_id: person.hunter
    event: enter
    platform: zone
    zone: zone.home
  - entity_id: binary_sensor.door_window_sensor_158d0001f38110
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: person.nikki
    event: enter
    platform: zone
    zone: zone.home
  condition:
  - condition: or
    conditions:
    - after: sunset
      after_offset: '-1:00:00'
      condition: sun
    - before: sunrise
      before_offset: '1:00:00'
      condition: sun
  action:
  - data:
      message: Welcome home
    service: notify.pushbullet
  - alias: ''
    entity_id: light.entry
    service: light.turn_on
- id: '1554985557227'
  alias: Weekday Tariff Change
  trigger:
  - at: '6:59'
    platform: time
  - at: '13:59'
    platform: time
  - at: '19:59'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: utility_meter.energy
    service: utility_meter.next_tariff
- id: '1554985905896'
  alias: Weekend Tariff Shoulder
  trigger:
  - at: 07:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - data:
      entity_id: utility_meter.energy
      tariff: shoulder
    service: utility_meter.select_tariff
- id: '1554985959342'
  alias: Weekend Tariff Peak
  trigger:
  - at: '22:00'
    platform: time
  condition:
  - condition: time
    weekday:
    - sat
    - sun
  action:
  - data:
      entity_id: utility_meter.energy
      tariff: offpeak
    service: utility_meter.select_tariff
- id: '1555116275673'
  alias: Kitchen timer notification
  trigger:
  - below: '1'
    entity_id: sensor.display_timer_remaining
    for: '45'
    platform: numeric_state
  condition: []
  action:
  - data:
      message: The kitchen display timer is ready
    service: notify.pushbullet
- id: '1555116490673'
  alias: Weekday Winter Tariff Change
  initial_state: 'false'
  trigger:
  - at: '6:59'
    platform: time
  - at: '16:59'
    platform: time
  - at: '20:59'
    platform: time
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: utility_meter.energy
    service: utility_meter.next_tariff
- id: '1555121570851'
  alias: Transition Winter Tariffs
  trigger:
  - entity_id: sensor.is_winter_tariff
    from: 'false'
    platform: state
    to: 'true'
  - entity_id: sensor.is_winter_tariff
    from: 'true'
    platform: state
    to: 'false'
  condition: []
  action:
  - data:
      entity_id: automation.weekday_tariff_change
    service: automation.toggle
  - data:
      entity_id: automation.weekday_winter_tariff_change
    service: automation.toggle
