homeassistant:
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 200
  unit_system: metric
  time_zone: Australia/Sydney
  customize: !include customize.yaml


# Enables the frontend
frontend:
# Enables configuration UI
config:

google_assistant:
  project_id: level-mark-166706
  client_id: !secret google_client_id
  access_token: !secret google_access_token
  agent_user_id: hunter
  api_key: !secret google_api_key
  exposed_domains:
    - light
    - cover
  entity_config:
    switch.Silvia:
    #  type: switch
      expose: true
    #media_player.Tunes:
    #  type: media_player
    #  expose: true
    switch.My_pc:
    #  type: switch
      expose: true
    switch.Gym_Speakers:
    #  type: switch
      expose: true

camera:
  - platform: generic
    still_image_url: http://10.0.0.10/image/jpeg.cgi
    username: !secret camera_username
    password: !secret camera_password
    name: Entry Cam
  - platform: generic
    still_image_url: http://www.rms.nsw.gov.au/trafficreports/cameras/camera_images/f3_windybanks.jpg
    name: M1 Windybanks
  - platform: generic
    still_image_url: http://www.rms.nsw.gov.au/trafficreports/cameras/camera_images/f3_wahroonga.jpg
    name: M1 Wahroonga
  - platform: generic
    still_image_url: http://www.rms.nsw.gov.au/trafficreports/cameras/camera_images/pacific_chats.jpg
    name: Chatswood
  - platform: generic
    still_image_url: http://www.rms.nsw.gov.au/trafficreports/cameras/camera_images/pennanthillsrd_thornleigh.jpg
    name: Thornleigh

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  trusted_networks:
    - 10.0.0.0/24
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
  - platform: netgear
    host: 10.0.0.1
    username: !secret router_username
    password: !secret router_password
    consider_home: 340
    interval_seconds: 12
    track_new_devices: yes

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sensor.last_boot
      - sensor.date

#recorder:
#  exclude:
#    domains:
#      - automation
#      - weblink
#      - updater
#    entities:
#      - sun.sun
#      - sensor.date

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.garage_door_time_in_state
      - sensor.garage_door_wifi_signal_strength
    domains:
      - sun
      - weblink

# Track the sun
sun:

sensor: !include sensor.yaml
scene: !include scene.yaml
automation: !include automations.yaml

logger:
  default: error


# Text to speech
tts:
  platform: google

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  protocol: 3.1

switch:
#  - platform: mqtt
#    command_topic: "$device/80d5a43df8/channel/1-6-in"
#    name: Silvia
#    payload_on: '{"Method":"turnOn","params":null,"JsonRpc":"2.0"}'
#    payload_off: '{"Method":"turnOff","params":null,"JsonRpc":"2.0"}'
#    qos: 0
  - platform: xiaomi_miio
    name: Silvia
    host: 10.0.0.7
    token: !secret silvia_token
  - platform: xiaomi_miio
    name: Gym Speakers
    host: 10.0.0.8
    token: !secret bathroom_fan_token
  - platform: flux
    name: flux
    lights:
    - light.study
    - light.dining_table
    - light.lounge
    - light.Bedroom
    - light.Entry
    - light.Hallway
    #- light.Stairs
    mode: mired
    disable_brightness_adjust: True
  - platform: wake_on_lan
    name: My PC
    mac_address: "ac:22:0b:26:15:08"
    host: 10.0.0.2
    turn_off:
      service: switch.turn_off
      entity_id: switch.pc
  - platform: command_line
    switches:
      pc:
        command_off: !secret pc_shutdown_command


media_player:
  - platform: gpmdp
    name: Tunes
    host: 10.0.0.2
  - platform: cast
    name: TV
    host: 10.0.0.18
  - platform: cast
    name: Gym Speaker
    host: 10.0.0.20
  - platform: samsungtv
    host: 10.0.0.55
    port: 8001
    name: Samsung TV
    mac: BC:8C:CD:C1:28:3F

notify:
  - name: Pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

light: !include light.yaml
group: !include groups.yaml
script: !include scripts.yaml

cover:
  - platform: garadget
    covers:
      480056000551353530353431:
        username: !secret garadget_user
        password: !secret garadget_password
        name: Garage door

input_datetime:
  weekday_wakeup_time:
    name: Weekday Wake-up Time
    has_date: false
    has_time: true
    initial: '07:15'
  weekend_wakeup_time:
    name: Weekend Wake-up Time
    has_date: false
    has_time: true
    initial: '10:00'


xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_password

zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 200
  icon: mdi:home

zone 2:
  name: Work
  radius: 200
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  icon: mdi:laptop

zone 3:
  name: Main Work
  radius: 200
  latitude: !secret nwork_latitude
  longitude: !secret nwork_longitude
  icon: mdi:medical-bag

zone 4:
  name: Work
  radius: 200
  latitude: !secret nwork2_latitude
  longitude: !secret nwork2_longitude
  icon: mdi:medical-bag
