homeassistant:
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 200
  unit_system: metric
  time_zone: Australia/Sydney
  customize: !include customize.yaml
  auth_providers:
   - type: homeassistant
   - type: trusted_networks
     trusted_networks:
       - 10.0.0.0/24

weather:
  - platform: darksky
    api_key: !secret darksky_key

# Enables the frontend
frontend:
# Enables configuration UI
config:

logger:
  default: warning

lovelace:
  mode: yaml

wake_on_lan:

system_health:

google_assistant:
  project_id: level-mark-166706
  api_key: !secret google_api_key
  exposed_domains:
    - light
    - cover
  entity_config:
    switch.Silvia:
      expose: true
    switch.plug_158d00020f3b00:
      expose: true
    switch.My_pc:
      expose: true
    switch.Gym_Speakers:
      expose: true
    media_player.living_room_tv:
      expose: true
    media_player.tunes:
      expose: true

googlehome:
  devices:
    - host: 10.0.0.16
      track_alarms: true
      #device_types: 1
    - host: 10.0.0.12
    - host: 10.0.0.13

cast:

map:

geo_location:
  - platform: nsw_rural_fire_service_feed

stream:

camera:
  - platform: generic
    still_image_url: http://10.0.0.10/image/jpeg.cgi
    #stream_source: http://10.0.0.10/VIDEO.CGI
    username: !secret camera_username
    password: !secret camera_password
    name: Entry Cam
  - platform: generic
    still_image_url: http://www.rms.nsw.gov.au/trafficreports/cameras/camera_images/f3_windybanks.jpg
    name: M1 Windybanks
  - platform: generic
    still_image_url: http://www.rms.nsw.gov.au/trafficreports/cameras/camera_images/f3_wahroonga.jpg
    name: M1 Wahroonga
  - platform: generic
    still_image_url: http://www.rms.nsw.gov.au/trafficreports/cameras/camera_images/pacific_chats.jpg
    name: Chatswood
  - platform: generic
    still_image_url: http://www.rms.nsw.gov.au/trafficreports/cameras/camera_images/pennanthillsrd_thornleigh.jpg
    name: Thornleigh



http:
  # Uncomment this to add a password (recommended!)
  #api_password: !secret http_password
  #trusted_networks:
  # Uncomment this if you are using SSL or running in Docker etc
  base_url: !secret base_url
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

device_tracker:
 # - platform: owntracks
 #   max_gps_accuracy: 200
  - platform: netgear
    host: 10.0.0.1
    username: !secret router_username
    password: !secret router_password
    consider_home: 900
    interval_seconds: 12
    track_new_devices: yes
    new_device_defaults:
      track_new_devices: false
  - platform: bluetooth_tracker

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - automation
      - weblink
      - updater
      - cover
      - camera
      - time
      - sun
      - device_tracker
      - group
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.garage_door_time_in_state
      - sensor.garage_door_wifi_signal_strength
      - sensor.garage_door_status
      - sensor.sonarr_upcoming
      - sensor.time
      - sensor.illumination_7811dcb20b46
      - sensor.ssl_certificate_expiry

# View all events in a logbook
logbook:
  exclude:
    entities:
      - sensor.last_boot
      - sensor.date
      - sensor.garage_door_time_in_state
      - sensor.garage_door_wifi_signal_strength
      - sensor.garage_door_status
      - sensor.sonarr_upcoming
      - sensor.time
      - sensor.illumination_7811dcb20b46
      - sensor.ssl_certificate_expiry
    domains:
      - weblink
      - updater
      - cover
      - camera
      - time
      - sun
      - device_tracker
      - group

# Track the sun
sun:

sensor: !include sensor.yaml
scene: !include scene.yaml
automation: !include automations.yaml



# Text to speech
tts:
  platform: google

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  protocol: 3.1
  discovery: true
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'

switch:
#  - platform: mqtt
#    command_topic: "$device/80d5a43df8/channel/1-6-in"
#    name: Silvia
#    payload_on: '{"Method":"turnOn","params":null,"JsonRpc":"2.0"}'
#    payload_off: '{"Method":"turnOff","params":null,"JsonRpc":"2.0"}'
#    qos: 0
  - platform: mqtt
    name: "Zigbee2mqtt Main join"
    state_topic: "zigbee2mqtt/bridge/config/permit_join"
    command_topic: "zigbee2mqtt/bridge/config/permit_join"
    payload_on: "true"
    payload_off: "false"
  - platform: xiaomi_miio
    name: Silvia
    host: 10.0.0.7
    token: !secret silvia_token
  - platform: xiaomi_miio
    name: Gym Speakers
    host: 10.0.0.8
    token: !secret bathroom_fan_token
  - platform: flux
    name: flux
    lights:
    - light.study
    - light.dining_table
    - light.lounge
    - light.Bedroom
    - light.Entry
    - light.Hallway
    #- light.Stairs
    mode: mired
    disable_brightness_adjust: True
  - platform: wake_on_lan
    name: My PC
    mac_address: "AC:22:0B:26:15:08"
    host: 10.0.0.2
    turn_off:
      service: switch.turn_off
      entity_id: switch.pc
  - platform: command_line
    switches:
      pc:
        command_off: !secret pc_shutdown_command


media_player:
  - platform: gpmdp
    name: Tunes
    host: 10.0.0.2
  - platform: webostv
    host: 10.0.0.21
    name: Living Room TV
    timeout: 5
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "2C:2B:F9:32:D6:2E"
    customize:
      sources:
        - livetv
        - steamlink
        - chromecast
        - youtube
        - foxtel
        - netflix
        - amazon

notify:
  - name: Pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_key

light: !include light.yaml
group: !include groups.yaml
script: !include scripts.yaml

cover:
  - platform: garadget
    covers:
      garage_door:
        device: !secret garadget_device_id
        username: !secret garadget_user
        password: !secret garadget_password
        name: Garage door

input_datetime:
  weekday_wakeup_time:
    name: Weekday Wake-up Time
    has_date: false
    has_time: true
    initial: '06:57'
  weekend_wakeup_time:
    name: Weekend Wake-up Time
    has_date: false
    has_time: true
    initial: '9:00'
input_number:
  peak_tariff_rate:
    name: Peak
    max: 100
    min: 0
    initial: 53.8
    step: 0.01
    unit_of_measurement: c
  offpeak_tariff_rate:
    name: Off Peak
    max: 100
    min: 0
    initial: 14.78
    step: 0.01
    unit_of_measurement: c
  shoulder_tariff_rate:
    name: Shoulder
    max: 100
    min: 0
    initial: 24.21
    step: 0.01
    unit_of_measurement: c
input_boolean:
  zigbee_permit_join:
    name: Allow devices to join
    initial: off
    icon: mdi:cellphone-wireless
input_select:
  zigbee2mqtt_log_level:
    name: Zigbee2mqtt Log Level
    options:
     - debug
     - info
     - warn
     - error
    initial: info
    icon: mdi:format-list-bulleted
timer:
  zigbee_permit_join:
    name: Time remaining
    duration: 120

utility_meter:
  energy:
    source: sensor.realtime_power
    cycle: daily
    tariffs:
      - offpeak
      - shoulder
      - peak


#xiaomi_aqara:
#  discovery_retry: 5
#  gateways:
#    - key: !secret xiaomi_password

person:

zone:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 200
  icon: mdi:home

zone 2:
  name: Work
  radius: 200
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  icon: mdi:laptop

zone 3:
  name: Main Work
  radius: 200
  latitude: !secret nwork_latitude
  longitude: !secret nwork_longitude
  icon: mdi:medical-bag

zone 4:
  name: Work
  radius: 200
  latitude: !secret nwork2_latitude
  longitude: !secret nwork2_longitude
  icon: mdi:medical-bag

speedtestdotnet:
  scan_interval:
    hours: 4
  monitored_conditions:
    - ping
    - download
    - upload

binary_sensor:
  - platform: workday
    country: AU
    province: NSW

plant:
    basil:
      sensors:
        moisture: sensor.basil_moisture
        temperature: sensor.basil_temperature
        conductivity: sensor.basil_conductivity
        brightness: sensor.basil_light_intensity
      min_moisture: 30
